### ISSUE TITLE
Android 5.0 Video Less Than 5 Seconds Encoding Error

### ISSUE THREAD

**Issue by seungyong** [nrikiji/cordova-plugin-video-trimming-editor#4]
If the video length is less than 5 seconds in "Android 5.0 Version" the image will not appear correctly.

**Comment by nrikiji** [comment]
Sorry, I overlooked it. I will confirm from now on.

**Comment by nrikiji** [comment]
This is probably a problem with the original library. There are no plans to get involved directly. I'm sorry.

Once closed.
