### ISSUE TITLE
Plugin not working at all 

### ISSUE THREAD

**Issue by shaktis110** [nrikiji/cordova-plugin-video-trimming-editor#5]
Hey man . Thanks for this awesome project 
I have installed the plugin everything works fine but when I call open method of plugin with path to video as argument nothing happens even no error shown up. ?? Is there something I am missing help me out. Any help will be appreciated...

**Comment by shaktis110** [comment]
As from my observation of the plugin folder everything looks right in first glance.

**Comment by shaktis110** [comment]
i have made some changes and its working now .. thanks

**Comment by nrikiji** [comment]
sory...I just checked.
It was nice to resolve. Thank you

**Comment by shaktis110** [comment]
Thank u for this awesome project.... 🙂

**Comment by shaktis110** [comment]
Do you have any plan on audio trim???
